name: torcharc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - flaky=3.6.1
  - numpy=1.18.1
  - pytest=5.4.1
  - pytest-cov=2.8.1
  - pytest-timeout=1.3.4
  - pytorch=1.5.0
  - pip:
    - pydash==4.7.6
    - git+https://github.com/kengz/transformer.git
