name: torcharc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - flaky=3.6.1
  - numpy=1.21.2
  - pytest=5.4.1
  - pytest-cov=2.8.1
  - pytest-timeout=1.3.4
  - pytorch=1.9.1
  - pip:
      - einops==0.3.2
      - pydash==4.7.6
