modules:
  head_0:
    Linear:
      in_features: 32
      out_features: 10
  head_1:
    Linear:
      in_features: 32
      out_features: 10
  merge_1_2:
    MergeProd:
  tail:
    Linear:
      in_features: 10
      out_features: 1

graph:
  input: [x_0, x_1]
  modules:
    head_0: [x_0]
    head_1: [x_1]
    merge_1_2: [head_0, head_1]
    tail: [merge_1_2]
  output: tail
