name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - uses: liskin/gh-problem-matcher-wrap@v1
        with:
          action: add
          linters: flake8

      - name: Lint with flake8
        run: |
          pip install flake8
          # exit-zero treats all errors as warnings.
          flake8 . --ignore=E501 --count --exit-zero --statistics

      - uses: liskin/gh-problem-matcher-wrap@v1
        with:
          action: remove
          linters: flake8

  build:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install repo
        run: |
          pip install torch -y
          pip install -e .

      - uses: liskin/gh-problem-matcher-wrap@v1
        with:
          action: add
          linters: pytest

      - name: Run tests
        run: |
          pip install wheel
          python setup.py test | tee pytest-coverage.txt

      - name: Post coverage to PR comment
        uses: coroo/pytest-coverage-commentator@v1.0.2

      - uses: liskin/gh-problem-matcher-wrap@v1
        with:
          action: add
          linters: pytest
